#!/bin/bash
# Install (or refresh) the Polymarket paper bot systemd timer on the oracle box.
#
# Runs ON the EC2 box, by hand or via SSM. Idempotent; deploy_oracle.sh calls
# it on every real deploy, same as install_metaculus_timer.sh.
#
#   sudo bash /home/ubuntu/oracle-api/infra/install_polymarket_paper_timer.sh
#
# Also derives the bot's credentials file (.env.polymarket-paper) from the
# box's ORACLE_API_KEYS map when it is absent — preferring a `polymarket-paper`
# named entry, falling back to the `metaculus` relay entry (retro#725). The key
# value is never printed. If neither entry exists the timer fires and the
# service is skipped cleanly (ConditionPathExists).
set -euo pipefail

API_DIR="/home/ubuntu/oracle-api"
BOX_ENV="/home/ubuntu/truthmachine/.env"
ENV_FILE="/home/ubuntu/truthmachine/.env.polymarket-paper"
LEDGER_DIR="/home/ubuntu/truthmachine/data/polymarket_paper"

log() { echo "[install_polymarket_paper_timer $(date '+%H:%M:%S')] $*"; }

[[ $EUID -eq 0 ]] || { echo "must run as root (systemctl + /etc/systemd)"; exit 1; }

for unit in polymarket-paper.service polymarket-paper.timer; do
  src="$API_DIR/infra/$unit"
  [[ -f "$src" ]] || { echo "missing $src — is the checkout up to date?"; exit 1; }
  log "installing $unit"
  install -m 0644 "$src" "/etc/systemd/system/$unit"
done

# The bot's uv project needs its lockfile resolved once on the box (--frozen at
# run time refuses to resolve). Same pattern deploy_oracle.sh uses for api/.
if [[ -f "$API_DIR/polymarket_paper/uv.lock" ]]; then
  log "uv sync --frozen (polymarket_paper)"
  (cd "$API_DIR/polymarket_paper" && sudo -u ubuntu /home/ubuntu/.local/bin/uv sync --frozen --quiet) || log "WARN: uv sync failed; the service will fail until it succeeds"
fi

# Ledger directory owned by the user the service runs as; the API reads it.
install -d -m 0755 -o ubuntu -g ubuntu "$LEDGER_DIR"

# Derive the bot's credentials file once. Idempotent: an existing file is left
# alone (delete it to regenerate after adding a `polymarket-paper` entry).
if [[ ! -f "$ENV_FILE" && -f "$BOX_ENV" ]]; then
  if python3 - "$BOX_ENV" "$ENV_FILE" <<'PY'
import json, os, sys
box_env, out = sys.argv[1], sys.argv[2]
raw = None
with open(box_env, encoding="utf-8") as fh:
    for line in fh:
        if line.startswith("ORACLE_API_KEYS="):
            raw = line.rstrip("\n").split("=", 1)[1].strip()
if raw is None:
    sys.exit(2)
if raw[:1] in ("'", '"') and raw[-1:] == raw[:1]:
    raw = raw[1:-1]
keys = json.loads(raw)
for name in ("polymarket-paper", "metaculus"):
    entry = keys.get(name)
    if isinstance(entry, dict) and entry.get("key"):
        break
else:
    sys.exit(3)
fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
with os.fdopen(fd, "w", encoding="utf-8") as fh:
    fh.write(f"# generated by install_polymarket_paper_timer.sh from ORACLE_API_KEYS[{name}]; delete to regenerate\n")
    fh.write(f"ORACLE_API_KEY={entry['key']}\n")
print(name)
PY
  then
    chown ubuntu:ubuntu "$ENV_FILE"
    log "wrote $ENV_FILE from the ORACLE_API_KEYS map (value not shown)"
  else
    log "NOTE: no polymarket-paper/metaculus entry in ORACLE_API_KEYS; $ENV_FILE not written"
  fi
fi

log "daemon-reload"
systemctl daemon-reload

log "enabling timer"
systemctl enable --now polymarket-paper.timer

log "--- next scheduled runs ---"
systemctl list-timers --no-pager polymarket-paper.timer || true

if [[ -f "$ENV_FILE" ]]; then
  log "credentials present at $ENV_FILE — the service will actually run"
  # Empty ledger = never ran. Kick one run now (in the background — the deploy
  # must not wait on Oracle calls) so the scorecard has rows before the next slot.
  if [[ ! -s "$LEDGER_DIR/snapshots.jsonl" ]]; then
    log "ledger empty — starting a first run in the background"
    systemctl start --no-block polymarket-paper.service || log "WARN: could not start a first run"
  fi
else
  log "NOTE: $ENV_FILE does not exist; every activation is SKIPPED by ConditionPathExists until it does."
fi

log "done. Follow runs with:  journalctl -u polymarket-paper.service -n 100"
