#!/usr/bin/env python3
"""
Generate graph_pm.json (the data-backed, backtestable graph) from the calibration
pipeline outputs — edge_weights.json for edges and node_history/ for priors.

This is the single source of truth that the backtest harness scores and that
pm_analysis should ultimately fetch instead of hand-syncing inline JS.

Run:  python bayesoracle/build_pm_graph.py
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).parent
EDGE_WEIGHTS = HERE / "edge_weights.json"
NODE_HISTORY = HERE / "node_history"
OUT = HERE / "graph_pm.json"

# Human labels + the mutually-exclusive PM-candidate group.
LABELS = {
    "CEASEFIRE_X": "Ceasefire breaks", "ELECTIONS": "Early elections",
    "BIBI_OUT": "Bibi not PM 2027", "BIBI_PM": "Bibi PM", "BENNETT_PM": "Bennett PM",
    "EIZENKOT_PM": "Eizenkot PM", "LIEBERMAN_PM": "Lieberman PM", "LAPID_PM": "Lapid PM",
    "ANNEX_WB": "W. Bank annexation", "ANNEX_GAZA": "Gaza annexation",
    "US_GAZA": "US administers Gaza", "TURKEY_CLASH": "Israel–Turkey clash",
    "SAUDI_NORM": "Saudi normalization", "SAUDI_ACCORDS": "Saudi joins Accords",
    "LEBANON_NORM": "Lebanon normalization", "SYRIA_NORM": "Syria normalization",
    "STRIKE_5": "2nd strike on Iran", "PAHLAVI": "Pahlavi recognized",
    "US_DECLARE": "US declares war on Iran", "IRAN_DEAL": "US–Iran deal",
    "IRAN_NUKE": "Iran nuclear test", "IRAN_REGIME": "Iran regime falls",
    "US_WAR_IRAN": "US attacks Iran", "TRUMP_IL": "Trump visits Israel",
}
PM_CANDIDATES = ["BIBI_PM", "BENNETT_PM", "EIZENKOT_PM", "LIEBERMAN_PM", "LAPID_PM"]


def latest_prior(node_id: str) -> float | None:
    f = NODE_HISTORY / f"{node_id}.json"
    if not f.exists():
        return None
    prices = json.loads(f.read_text()).get("prices", [])
    if not prices:
        return None
    return float(sorted(prices, key=lambda p: p["date"])[-1]["probability"])


def main() -> None:
    edges_raw = json.loads(EDGE_WEIGHTS.read_text())
    node_ids = sorted(p.stem for p in NODE_HISTORY.glob("*.json") if p.stem != "all")

    nodes = []
    for nid in node_ids:
        prior = latest_prior(nid)
        if prior is None:
            continue
        nodes.append({
            "id": nid,
            "label": LABELS.get(nid, nid),
            "prior": round(min(0.99, max(0.01, prior)), 4),
        })
    present = {n["id"] for n in nodes}

    edges = []
    for e in edges_raw:
        if e["source"] not in present or e["target"] not in present:
            continue
        pY = e.get("pY_blend", e.get("pY"))
        pN = e.get("pN_blend", e.get("pN"))
        edges.append({
            "source": e["source"], "target": e["target"],
            "pYes": round(float(pY), 4), "pNo": round(float(pN), 4),
            "type": e.get("type", "primary"),
        })

    # Assign layers by longest-path depth from roots (for presentation/topo stability).
    parents: dict[str, list[str]] = {}
    for e in edges:
        parents.setdefault(e["target"], []).append(e["source"])
    depth: dict[str, int] = {}

    def d(nid: str, seen: frozenset = frozenset()) -> int:
        if nid in depth:
            return depth[nid]
        ps = [p for p in parents.get(nid, []) if p not in seen]
        depth[nid] = 0 if not ps else 1 + max(d(p, seen | {nid}) for p in ps)
        return depth[nid]

    for n in nodes:
        n["layer"] = d(n["id"])

    spec = {
        "name": "Israeli Politics 2026 — Polymarket-backed DAG",
        "as_of": max(
            json.loads((NODE_HISTORY / f"{n['id']}.json").read_text())["prices"][-1]["date"]
            for n in nodes
        ),
        "notes": "Auto-generated by build_pm_graph.py from edge_weights.json (edges) "
                 "and node_history/ (priors = latest PM price). Do not hand-edit.",
        "nodes": sorted(nodes, key=lambda n: (n["layer"], n["id"])),
        "edges": edges,
        "exclusive_groups": [
            {"id": "next_pm", "members": [c for c in PM_CANDIDATES if c in present],
             "allow_other": True}
        ],
    }
    OUT.write_text(json.dumps(spec, indent=2) + "\n")
    print(f"wrote {OUT}  ({len(nodes)} nodes, {len(edges)} edges, as_of {spec['as_of']})")


if __name__ == "__main__":
    main()
