// AUTO-GENERATED from graph_pm.json by gen_viewers.py — do not edit.
window.GRAPH_PM = {
  "name": "Israeli Politics 2026 \u2014 Polymarket-backed DAG",
  "as_of": "2026-06-03",
  "notes": "Auto-generated by build_pm_graph.py from edge_weights.json (edges) and node_history/ (priors = latest PM price). Do not hand-edit.",
  "nodes": [
    {
      "id": "CEASEFIRE_X",
      "label": "Ceasefire breaks",
      "prior": 0.105,
      "layer": 0
    },
    {
      "id": "IRAN_DEAL",
      "label": "US\u2013Iran deal",
      "prior": 0.64,
      "layer": 0
    },
    {
      "id": "IRAN_NUKE",
      "label": "Iran nuclear test",
      "prior": 0.08,
      "layer": 0
    },
    {
      "id": "IRAN_REGIME",
      "label": "Iran regime falls",
      "prior": 0.135,
      "layer": 0
    },
    {
      "id": "TRUMP_IL",
      "label": "Trump visits Israel",
      "prior": 0.345,
      "layer": 0
    },
    {
      "id": "US_WAR_IRAN",
      "label": "US attacks Iran",
      "prior": 0.175,
      "layer": 0
    },
    {
      "id": "ELECTIONS",
      "label": "Early elections",
      "prior": 0.445,
      "layer": 1
    },
    {
      "id": "PAHLAVI",
      "label": "Pahlavi recognized",
      "prior": 0.075,
      "layer": 1
    },
    {
      "id": "US_DECLARE",
      "label": "US declares war on Iran",
      "prior": 0.065,
      "layer": 1
    },
    {
      "id": "BIBI_OUT",
      "label": "Bibi not PM 2027",
      "prior": 0.495,
      "layer": 2
    },
    {
      "id": "BENNETT_PM",
      "label": "Bennett PM",
      "prior": 0.305,
      "layer": 3
    },
    {
      "id": "BIBI_PM",
      "label": "Bibi PM",
      "prior": 0.335,
      "layer": 3
    },
    {
      "id": "EIZENKOT_PM",
      "label": "Eizenkot PM",
      "prior": 0.2365,
      "layer": 3
    },
    {
      "id": "LAPID_PM",
      "label": "Lapid PM",
      "prior": 0.01,
      "layer": 3
    },
    {
      "id": "LIEBERMAN_PM",
      "label": "Lieberman PM",
      "prior": 0.0415,
      "layer": 3
    },
    {
      "id": "ANNEX_GAZA",
      "label": "Gaza annexation",
      "prior": 0.023,
      "layer": 4
    },
    {
      "id": "ANNEX_WB",
      "label": "W. Bank annexation",
      "prior": 0.105,
      "layer": 4
    },
    {
      "id": "LEBANON_NORM",
      "label": "Lebanon normalization",
      "prior": 0.2,
      "layer": 4
    },
    {
      "id": "SAUDI_ACCORDS",
      "label": "Saudi joins Accords",
      "prior": 0.13,
      "layer": 4
    },
    {
      "id": "SAUDI_NORM",
      "label": "Saudi normalization",
      "prior": 0.135,
      "layer": 4
    },
    {
      "id": "STRIKE_5",
      "label": "2nd strike on Iran",
      "prior": 0.3075,
      "layer": 4
    },
    {
      "id": "SYRIA_NORM",
      "label": "Syria normalization",
      "prior": 0.12,
      "layer": 4
    },
    {
      "id": "TURKEY_CLASH",
      "label": "Israel\u2013Turkey clash",
      "prior": 0.15,
      "layer": 4
    },
    {
      "id": "US_GAZA",
      "label": "US administers Gaza",
      "prior": 0.15,
      "layer": 4
    }
  ],
  "edges": [
    {
      "source": "BIBI_OUT",
      "target": "BIBI_PM",
      "pYes": 0.296,
      "pNo": 0.608,
      "type": "primary"
    },
    {
      "source": "BIBI_OUT",
      "target": "EIZENKOT_PM",
      "pYes": 0.138,
      "pNo": 0.066,
      "type": "primary"
    },
    {
      "source": "BIBI_OUT",
      "target": "LIEBERMAN_PM",
      "pYes": 0.08,
      "pNo": 0.013,
      "type": "primary"
    },
    {
      "source": "BIBI_OUT",
      "target": "LAPID_PM",
      "pYes": 0.097,
      "pNo": 0.018,
      "type": "primary"
    },
    {
      "source": "CEASEFIRE_X",
      "target": "ELECTIONS",
      "pYes": 0.769,
      "pNo": 0.397,
      "type": "primary"
    },
    {
      "source": "ELECTIONS",
      "target": "BIBI_OUT",
      "pYes": 0.58,
      "pNo": 0.398,
      "type": "primary"
    },
    {
      "source": "BIBI_OUT",
      "target": "BENNETT_PM",
      "pYes": 0.51,
      "pNo": 0.242,
      "type": "primary"
    },
    {
      "source": "BIBI_PM",
      "target": "ANNEX_WB",
      "pYes": 0.321,
      "pNo": 0.09,
      "type": "primary"
    },
    {
      "source": "BIBI_PM",
      "target": "ANNEX_GAZA",
      "pYes": 0.147,
      "pNo": 0.032,
      "type": "primary"
    },
    {
      "source": "BIBI_PM",
      "target": "US_GAZA",
      "pYes": 0.485,
      "pNo": 0.167,
      "type": "primary"
    },
    {
      "source": "BIBI_PM",
      "target": "TURKEY_CLASH",
      "pYes": 0.279,
      "pNo": 0.151,
      "type": "primary"
    },
    {
      "source": "BIBI_PM",
      "target": "SAUDI_NORM",
      "pYes": 0.311,
      "pNo": 0.153,
      "type": "primary"
    },
    {
      "source": "BIBI_PM",
      "target": "SAUDI_ACCORDS",
      "pYes": 0.317,
      "pNo": 0.124,
      "type": "primary"
    },
    {
      "source": "BIBI_PM",
      "target": "LEBANON_NORM",
      "pYes": 0.348,
      "pNo": 0.176,
      "type": "primary"
    },
    {
      "source": "BIBI_PM",
      "target": "SYRIA_NORM",
      "pYes": 0.309,
      "pNo": 0.105,
      "type": "primary"
    },
    {
      "source": "IRAN_NUKE",
      "target": "STRIKE_5",
      "pYes": 0.349,
      "pNo": 0.175,
      "type": "primary"
    },
    {
      "source": "IRAN_REGIME",
      "target": "PAHLAVI",
      "pYes": 0.514,
      "pNo": 0.137,
      "type": "primary"
    },
    {
      "source": "US_WAR_IRAN",
      "target": "US_DECLARE",
      "pYes": 0.278,
      "pNo": 0.078,
      "type": "primary"
    },
    {
      "source": "IRAN_DEAL",
      "target": "ELECTIONS",
      "pYes": 0.467,
      "pNo": 0.464,
      "type": "secondary"
    },
    {
      "source": "TRUMP_IL",
      "target": "ELECTIONS",
      "pYes": 0.46,
      "pNo": 0.523,
      "type": "secondary"
    },
    {
      "source": "CEASEFIRE_X",
      "target": "BIBI_OUT",
      "pYes": 0.567,
      "pNo": 0.452,
      "type": "secondary"
    },
    {
      "source": "TRUMP_IL",
      "target": "BIBI_OUT",
      "pYes": 0.516,
      "pNo": 0.459,
      "type": "secondary"
    },
    {
      "source": "TRUMP_IL",
      "target": "BIBI_PM",
      "pYes": 0.519,
      "pNo": 0.343,
      "type": "secondary"
    },
    {
      "source": "TRUMP_IL",
      "target": "STRIKE_5",
      "pYes": 0.158,
      "pNo": 0.301,
      "type": "secondary"
    },
    {
      "source": "IRAN_DEAL",
      "target": "STRIKE_5",
      "pYes": 0.257,
      "pNo": 0.152,
      "type": "secondary"
    },
    {
      "source": "BIBI_PM",
      "target": "STRIKE_5",
      "pYes": 0.264,
      "pNo": 0.282,
      "type": "secondary"
    },
    {
      "source": "US_WAR_IRAN",
      "target": "PAHLAVI",
      "pYes": 0.399,
      "pNo": 0.153,
      "type": "secondary"
    },
    {
      "source": "TRUMP_IL",
      "target": "US_DECLARE",
      "pYes": 0.105,
      "pNo": 0.052,
      "type": "secondary"
    }
  ],
  "exclusive_groups": [
    {
      "id": "next_pm",
      "members": [
        "BIBI_PM",
        "BENNETT_PM",
        "EIZENKOT_PM",
        "LIEBERMAN_PM",
        "LAPID_PM"
      ],
      "allow_other": true
    }
  ]
};
